### ISSUE TITLE
Moving to ClimateMARGO github organization

### ISSUE THREAD

**Issue by hdrake** [ClimateMARGO/ClimateMARGO.jl#56]
I'm thinking of moving ClimateMARGO.jl and all my related repos over to the new organization https://github.com/ClimateMARGO. It would be nice to move everything over there before 1) the paper is re-submitted and 2) we publicize our interactive web apps via the blog posts we've been working on.

I think Github handles re-directing the urls, but I don't know how long that services lasts or if it covers all use cases. It would be good to finalize the URLs for at least the key packages, documentation, main website (ClimateMARGO.github.io, at least until we get a better domain), etc.

What do you think @fonsp @jhamman @freeman-lab?

(P.S. I'm making great progress on the paper revisions finally and have some awesome new figures that I think you all will find interesting)

**Comment by fonsp** [comment]
Sure! Look forward to those new figures :)

**Comment by jhamman** [comment]
Sounds like a great idea! We're happy to move margo-js over whenever you are ready.

**Comment by hdrake** [comment]
Done– see https://github.com/ClimateMARGO
