### ISSUE TITLE
emissions to concentrations Q (unit_conversions.jl)

### ISSUE THREAD

**Issue by declann** [ClimateMARGO/ClimateMARGO.jl#86]
Hi guys!

Really like toying with ClimateMARGO and the informative notebooks and learning about a simple but useful climate model! Great work 🥳
Will like to release a simple climate model also, or recreate MARGO or do some exercises with it in a modelling langage ([calculang](https://github.com/calculang/calculang)) I develop - will reach out if I get results!

---

In my model I got stuck on **method/assumptions to convert emissions to concentrations**. I can see how MARGO does this in [`unit_conversions.jl`](https://github.com/ClimateMARGO/ClimateMARGO.jl/blob/main/src/Utils/unit_conversions.jl):

```julia
const year = 365.25 * 24. * 60. * 60.

GtCO2_to_ppm(GtCO2) = GtCO2 / (2.13 * (44. /12.))
tCO2_to_ppm(tCO2) = GtCO2_to_ppm(tCO2) * 1.e-9

ppm_to_GtCO2(ppm) = ppm * (2.13 * (44. /12.))
ppm_to_tCO2(ppm) = ppm_to_GtCO2(ppm) * 1.e9
```

Can you please provide any info or sources for the parameters/approach used here? (i.e. factor `2.13 * (44. /12.)`~=7.81)

Thanks!
Declan

**Comment by hdrake** [comment]
Hi @declann, that's great! Multiplying by [2.13 converts from parts per million CO2 to Gigatonnes of carbon](https://web.archive.org/web/20170118004650/http://cdiac.ornl.gov/pns/convert.html) and then multiplying by `44/12` gets us back to mass of CO2 (12u + 2*16u = 44u compared to 12u for just elementary carbon).

**Comment by declann** [comment]
Perfect, exactly what I needed, thanks very much Henri !
